export const HOME_ROUTE = '/'
export const AUTH_REG_ROUTE = '/authreg'
export const ADMIN_PANEL_ROUTE = '/admin_panel'
export const HINKALI_ROUTE = '/hinkali'
export const HACHAPURI_ROUTE = '/hachapuri'
export const MAIN_MEALS_ROUTE = '/mainmeals'
export const DRINKS_ROUTE = '/drinks'
export const CART_ROUTE = '/cart'